version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: chat_mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_DATABASE: chat
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /data/db:/data/db
